version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/opt/node_app/app
    ports:
      - 3000:3000
    # links:
    #   - db
    # environment: 
    #   - DB_HOST=db
    # command: npm start
  db:
    image: mongo
 